/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as crowdfundingSol from "./Crowdfunding.sol";
export type { crowdfundingSol };
import type * as testSol from "./test.sol";
export type { testSol };
export * as factories from "./factories";
export type { Crowfunding } from "./Crowdfunding.sol/Crowfunding";
export { Crowfunding__factory } from "./factories/Crowdfunding.sol/Crowfunding__factory";
export type { CrowdFunding } from "./test.sol/CrowdFunding";
export { CrowdFunding__factory } from "./factories/test.sol/CrowdFunding__factory";
